version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=redispassword
    restart: always
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"
    environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./cassandra:/var/lib/cassandr
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    volumes:
      - ./es:/data/es-data
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.0
    restart: always
    ports:
      - "5601:5601"
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
